@testtoken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InZKaTB5Z0FWd0ZhcnFCZk9sODAzLSJ9.eyJpc3MiOiJodHRwczovL2Rldi1pc2RzbnpsNThwZ214M2t3LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJiYU1SSFpoaVUwanRwbWRXQ1JJeGV1RGhIUFo2NmRSMUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9zYXZlZm9ycGVya3MuY29tIiwiaWF0IjoxNzcxMjM2MDE4LCJleHAiOjE3NzEzMjI0MTgsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsImF6cCI6ImJhTVJIWmhpVTBqdHBtZFdDUkl4ZXVEaEhQWjY2ZFIxIn0.CtJotFYcdaIjEUvxXYfW18ITRnWP4VKSQwPB4N2rGX_WeZf6hc18jULYmHafmJUwzW4LfCWwZSvOD3oiq0pJzxdalMktgphyTdtMSwRGlMIiAvN18aGAhoc-_SWlC_O6oY-653qEfQeirfLwIjPHYmURUce9uGj8j6iie3r2YSJlNfkFz6_ZWutfJkyVU7SbUkIma6GQWCMckJ92KM_MmLE1qHyDwBu6m38iMSFlUrSpK6BlWdhc550L4Oc0RkNT2osXrUOek1t4AN5r9GlayqVF-gv2qRA-O08LT9AvDo53npfzwlScT7LG2XQoaG9vuXFh6eQAK84PVMVmZG1Hmw
@url = http://localhost:5143/api/
@contentType = application/json

@auth0UserId = auth0|698b36c760e655fa928e76b8
@businessId = 75B8DDC5-5162-454D-A4CB-D945C00ED74B
@businessUserId = 46C48332-E633-43D7-BB4C-C66322F56535
@rewardId = f11a2397-e293-4ecf-bac7-ab8cf18d812d
@customerId = 3E2D99B8-3B81-4880-B151-FE6FA95600E6

# *************** HEALTH CHECK **************************

###
GET {{url}}health


# *************** ADMIN **************************

###
GET {{url}}admin/businesses


# *************** Business **************************

# Step 10 - Create a new business along with the first business user who will be set to admin.
###
POST {{url}}business
Content-Type: application/json

{
"BusinessName": "Joes coffee shop",
"BusinessDescription": "A nice coffee sop",
"BusinessCategoryId": "22222222-2222-2222-2222-222222222222",
"BusinessUserAuthProviderId": "auth01234",
"BusinessUserEmail": "joe@example.com",
"BusinessUserName": "Joe Admin"
}

# ***************** BusinessUser ***************************
# Step 20 - Get the Business details for a BusinessUser - DEPRECATED
###
GET {{url}}business-user/auth01234/businesses

# Reward Owner User - DEPRECATED
# Step 1: Get RewardOwnerUser by AuthProviderId
###
GET {{url}}business-user/by-auth/auth0|6978c6069f7c25664b0c13cf

# Use this instead
# Step 30 Get BusinessUser and Business details and see if Business.Name has been completed (BusinessProfileExists) 
### Combine above two into one call
GET {{url}}business-user/profile/{{auth0UserId}}

# END Reward Owner User



# Get Rewards for a businessId
# Step 30
###
GET {{url}}business/{{businessId}}/rewards
X-BusinessUser-Id: {{businessUserId}}

# Create a new Reward
###
POST {{url}}business/{{businessId}}/rewards
X-BusinessUser-Id: {{businessUserId}}
Content-Type: application/json

{
  "name": "Free Coffee",
  "rewardType": "IncrementalPoints",
  "costPoints": 10
}

# Update a reward
###
PUT {{url}}business/{{businessId}}/rewards/{{rewardId}}
Content-Type: application/json
X-BusinessUser-Id: {{businessUserId}}

{
  "name": "Buy 5 loaves and get 1 free (Updated)",
  "rewardType": "IncrementalPoints",
  "costPoints": 3,
  "isActive": true
}



# Business Category
###
GET {{url}}business-category


# Initial scan of qr code
###
GET {{url}}business/{{businessId}}/scans/{{rewardId}}/customerbalance/QR001-ALICE-9999


# 1 Expect current balance of 2
# Scan a users qr code to claim points for a reward and also reward redemption
###
POST {{url}}business/{{businessId}}/scans
X-BusinessUser-Id: {{businessUserId}}
Content-Type: application/json

{
  "RewardId": "ED83EB01-C41A-4AE7-8A41-D741C2F093E8",
  "QrCodeValue": "QR003-CHARLIE-BBBB", 
  "PointsChange": 4,
  "NumRewardsToClaim": 4
}



# Customer
###
GET {{url}}customer/by-auth/{{auth0UserId}}


# Create a new customer.
###
POST {{url}}customer
Content-Type: application/json

{
"AuthProviderId": "auth01237",
"Email": "customer@example.com",
"Name": "Joe Customer"
}

# Get dashboard info for a customer
###
GET {{url}}customer/{{customerId}}/dashboard
Authorization: Bearer  {{testtoken}}

# Delete a customer
###
DELETE {{url}}customer/{{customerId}}