@testtoken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InZKaTB5Z0FWd0ZhcnFCZk9sODAzLSJ9.eyJpc3MiOiJodHRwczovL2Rldi1pc2RzbnpsNThwZ214M2t3LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJyTEZncGlXNml6WVFRWDUyc0JqQ29qbThwZjA3d1RnekBjbGllbnRzIiwiYXVkIjoidGltZXRyYWNrZXIiLCJpYXQiOjE3NjMyMjU4MTgsImV4cCI6MTc2MzMxMjIxOCwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIiwiYXpwIjoickxGZ3BpVzZpellRUVg1MnNCakNvam04cGYwN3dUZ3oifQ.UnAqA5vO0XQsmIOlDinUAx6gaYnPGlOQuib4N0x0r1hXYAyECIfZcTuGIVmNHcrG0mZLamCo5-vHhahHjq0kEydXK-votzA_6Z__GKW1L7KouPePlleEX3kWtsCryV1URYmZF53j2GiGAk6wb6ZTXsWH0pPW-b2y8rBb84rto6gm2PP3iKRqsuqG3eOkf_8TVTQTxxwZNvtCttAM5c1hH2beKNPTkhEZgXH7HsFi5ckJRLipINhvVYL_yM18sHIt5Pn-2BXm0sfwdCkb1XFwPO745_eSCV6tsCZjDga1lIN1eFEFq8GOsurn_muqgF2WEK2DBUj_8S722xFJ2ErDRg
# @url = https://saveforperks-webapi-g4cpbzf4dpbqd9cd.uksouth-01.azurewebsites.net/api/
@url = http://localhost:5143/api/
@contentType = application/json
@businessUserId = A2222222-2222-2222-2222-222222222222

# *************** HEALTH CHECK **************************

###
GET {{url}}health


# *************** ADMIN **************************

###
GET {{url}}admin/businesses


# *************** Business **************************

# Step 10 - Create a new business along with the first business user who will be set to admin.
###
POST {{url}}business
Content-Type: application/json

{
"BusinessName": "Joes coffee shop",
"BusinessDescription": "A nice coffee sop",
"BusinessCategoryId": "22222222-2222-2222-2222-222222222222",
"BusinessUserAuthProviderId": "auth01234",
"BusinessUserEmail": "joe@example.com",
"BusinessUserName": "Joe Admin"
}

# ***************** BusinessUser ***************************
# Step 20 - Get the Business details for a BusinessUser - DEPRECATED
###
GET {{url}}business-user/auth01234/businesses

# Reward Owner User - DEPRECATED
# Step 1: Get RewardOwnerUser by AuthProviderId
###
GET {{url}}business-user/by-auth/auth0|6978c6069f7c25664b0c13cf

# Use this instead
# Step 30 Get BusinessUser and Business details and see if Business.Name has been completed (BusinessProfileExists) 
### Combine above two into one call
GET {{url}}business-user/profile/auth01234

# END Reward Owner User



# Get Rewards for a businessId
# Step 30
###
GET {{url}}business/22222222-2222-2222-2222-222222222222/rewards
X-BusinessUser-Id: {{businessUserId}}

# Create a new Reward
###
POST {{url}}business/22222222-2222-2222-2222-222222222222/rewards
X-BusinessUser-Id: {{businessUserId}}
Content-Type: application/json

{
  "name": "Free Coffee",
  "rewardType": "IncrementalPoints",
  "costPoints": 10
}

# Business Category
###
GET {{url}}business-category


# Initial scan of qr code
###
@businessId = 22222222-2222-2222-2222-222222222222
@rewardId = ED83EB01-C41A-4AE7-8A41-D741C2F093E8
GET {{url}}business/{{businessId}}/scans/{{rewardId}}/customerbalance/QR001-ALICE-9999


# 1 Expect current balance of 2
# Scan a users qr code to claim points for a reward and also reward redemption
###
@businessId = 22222222-2222-2222-2222-222222222222
@businessUserId = A2222222-2222-2222-2222-222222222222
POST {{url}}business/{{businessId}}/scans
X-BusinessUser-Id: {{businessUserId}}
Content-Type: application/json

{
  "RewardId": "ED83EB01-C41A-4AE7-8A41-D741C2F093E8",
  "QrCodeValue": "QR003-CHARLIE-BBBB", 
  "PointsChange": 4,
  "NumRewardsToClaim": 4
}



# Customer
###
@auth0UserId = auth0|user002
GET {{url}}customer/by-auth/{{auth0UserId}}


# Create a new customer.
###
POST {{url}}customer
Content-Type: application/json

{
"AuthProviderId": "auth01237",
"Email": "customer@example.com",
"Name": "Joe Customer"
}