// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaveForPerksAPI.DbContexts;

#nullable disable

namespace SaveForPerksAPI.Migrations
{
    [DbContext(typeof(TapForPerksContext))]
    [Migration("20260129135559_RenameUsersToUser")]
    partial class RenameUsersToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SaveForPerksAPI.Entities.Reward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("CostPoints")
                        .HasColumnType("int")
                        .HasColumnName("cost_points");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("RewardOwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reward_owner_id");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("reward_type");

                    b.HasKey("Id")
                        .HasName("PK__reward___3213E83F9D47D4D7");

                    b.HasIndex(new[] { "RewardOwnerId" }, "idx_reward_owner_id");

                    b.ToTable("reward", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CostPoints = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Pay for 5 coffees, get sixth free",
                            RewardOwnerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RewardType = "incremental_points"
                        });
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.RewardOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__reward___3213E83FEC734646");

                    b.ToTable("reward_owner", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "123 High Street, London, UK",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium artisan coffee shop chain",
                            Name = "The Daily Grind Coffee"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Address = "456 Market Square, Manchester, UK",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Private event",
                            Name = "Smith-Jones Wedding"
                        });
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.RewardOwnerUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AuthProviderId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("auth_provider_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("is_admin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("RewardOwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reward_owner_id");

                    b.HasKey("Id")
                        .HasName("PK__reward___3213E83FCA9F25E5");

                    b.HasIndex(new[] { "RewardOwnerId" }, "idx_reward_owner_user_owner_id");

                    b.ToTable("reward_owner_user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            AuthProviderId = "auth0|admin001",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "baristaone@dailygrind.com",
                            IsAdmin = true,
                            Name = "Barista One",
                            RewardOwnerId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            AuthProviderId = "auth0|admin002",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "host@wedding.com",
                            IsAdmin = true,
                            Name = "Wedding Host",
                            RewardOwnerId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.RewardRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("RedeemedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("redeemed_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("RewardId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reward_id");

                    b.Property<Guid?>("RewardOwnerUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reward_owner_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__reward_r__3213E83FC9ADA235");

                    b.HasIndex("RewardOwnerUserId");

                    b.HasIndex(new[] { "RewardId" }, "idx_reward_redemption_reward_id");

                    b.HasIndex(new[] { "UserId" }, "idx_reward_redemption_user_id");

                    b.ToTable("reward_redemption", (string)null);
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.ScanEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("PointsChange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("points_change");

                    b.Property<string>("QrCodeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("qr_code_value");

                    b.Property<Guid>("RewardId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reward_id");

                    b.Property<Guid?>("RewardOwnerUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reward_owner_user_id");

                    b.Property<DateTime>("ScannedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("scanned_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__scan_eve__3213E83F45201827");

                    b.HasIndex("RewardOwnerUserId");

                    b.HasIndex(new[] { "RewardId" }, "idx_scan_event_programme_id");

                    b.HasIndex(new[] { "UserId" }, "idx_scan_event_user_id");

                    b.ToTable("scan_event", (string)null);
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AuthProviderId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("auth_provider_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("QrCodeValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("qr_code_value");

                    b.HasKey("Id")
                        .HasName("PK__users__3213E83F4461F44E");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E6164CB0A1AE0")
                        .IsUnique();

                    b.HasIndex(new[] { "AuthProviderId" }, "UQ__users__C82CBBE99CDF45A3")
                        .IsUnique();

                    b.HasIndex(new[] { "QrCodeValue" }, "UQ__users__C8EB4B8153934E5A")
                        .IsUnique();

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            AuthProviderId = "auth0|user001",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice@example.com",
                            Name = "Alice Customer",
                            QrCodeValue = "QR001-ALICE-9999"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            AuthProviderId = "auth0|user002",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob@example.com",
                            Name = "Bob Customer",
                            QrCodeValue = "QR002-BOB-AAAA"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            AuthProviderId = "auth0|user003",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "charlie@example.com",
                            Name = "Charlie Customer",
                            QrCodeValue = "QR003-CHARLIE-BBBB"
                        });
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.UserBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("Balance")
                        .HasColumnType("int")
                        .HasColumnName("balance");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("RewardId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reward_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__user_bal__3213E83F23104F90");

                    b.HasIndex(new[] { "RewardId" }, "idx_user_balance_programme_id");

                    b.HasIndex(new[] { "UserId" }, "idx_user_balance_user_id");

                    b.HasIndex(new[] { "UserId", "RewardId" }, "uq_user_balance")
                        .IsUnique();

                    b.ToTable("user_balance", (string)null);
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.Reward", b =>
                {
                    b.HasOne("SaveForPerksAPI.Entities.RewardOwner", "RewardOwner")
                        .WithMany("Rewards")
                        .HasForeignKey("RewardOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reward_owner");

                    b.Navigation("RewardOwner");
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.RewardOwnerUser", b =>
                {
                    b.HasOne("SaveForPerksAPI.Entities.RewardOwner", "RewardOwner")
                        .WithMany("RewardOwnerUsers")
                        .HasForeignKey("RewardOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reward_owner_user_owner");

                    b.Navigation("RewardOwner");
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.RewardRedemption", b =>
                {
                    b.HasOne("SaveForPerksAPI.Entities.Reward", "Reward")
                        .WithMany("RewardRedemptions")
                        .HasForeignKey("RewardId")
                        .IsRequired()
                        .HasConstraintName("fk_reward_redemption_programme");

                    b.HasOne("SaveForPerksAPI.Entities.RewardOwnerUser", "RewardOwnerUser")
                        .WithMany("RewardRedemptions")
                        .HasForeignKey("RewardOwnerUserId")
                        .HasConstraintName("fk_reward_redemption_owner_user");

                    b.HasOne("SaveForPerksAPI.Entities.User", "User")
                        .WithMany("RewardRedemptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reward_redemption_user");

                    b.Navigation("Reward");

                    b.Navigation("RewardOwnerUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.ScanEvent", b =>
                {
                    b.HasOne("SaveForPerksAPI.Entities.Reward", "Reward")
                        .WithMany("ScanEvents")
                        .HasForeignKey("RewardId")
                        .IsRequired()
                        .HasConstraintName("fk_scan_event_programme");

                    b.HasOne("SaveForPerksAPI.Entities.RewardOwnerUser", "RewardOwnerUser")
                        .WithMany("ScanEvents")
                        .HasForeignKey("RewardOwnerUserId")
                        .HasConstraintName("fk_scan_event_owner_user");

                    b.HasOne("SaveForPerksAPI.Entities.User", "User")
                        .WithMany("ScanEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scan_event_user");

                    b.Navigation("Reward");

                    b.Navigation("RewardOwnerUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.UserBalance", b =>
                {
                    b.HasOne("SaveForPerksAPI.Entities.Reward", "Reward")
                        .WithMany("UserBalances")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_balance_programme");

                    b.HasOne("SaveForPerksAPI.Entities.User", "User")
                        .WithMany("UserBalances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_balance_user");

                    b.Navigation("Reward");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.Reward", b =>
                {
                    b.Navigation("RewardRedemptions");

                    b.Navigation("ScanEvents");

                    b.Navigation("UserBalances");
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.RewardOwner", b =>
                {
                    b.Navigation("RewardOwnerUsers");

                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.RewardOwnerUser", b =>
                {
                    b.Navigation("RewardRedemptions");

                    b.Navigation("ScanEvents");
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.User", b =>
                {
                    b.Navigation("RewardRedemptions");

                    b.Navigation("ScanEvents");

                    b.Navigation("UserBalances");
                });
#pragma warning restore 612, 618
        }
    }
}
